CURDIR=$(shell pwd)
PACKAGE_VERSION :=
PACKAGE_DIR :=
PACKAGE_CONF :=
first_rule: all

all: build

build:
	$(MAKE) -C $(CURDIR)/PACKAGE/SIP        first_rule
	$(MAKE) -C $(CURDIR)/PACKAGE/PyQt5      first_rule


config_rule:

install_rule install:

clean_rule distclean clean:

uninstall_rule uninstall:

